export const ROUTES = {
  // Root routes
  ROOT: "/",

  // Guest routes
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/password-reset",
  // Authenticated routes
  DASHBOARD: "/dashboard",
  ORDERS: "/orders",
  ORDERS_CREATE: "/orders/create",
  SUBSCRIPTIONS: "/subscriptions",
  COUPONS: "/coupons",
  PRODUCTS: "/products",
  PRODUCT_VARIATIONS: "/product-variations",
  JOURNEYS: "/journeys",
  JOURNEYS_CREATE: "/journeys/create",
  PATIENTS: "/patients",
  PATIENT_DETAIL: "/patients/:id",
  ENCOUNTERS: "/encounters",
  ENCOUNTERS_DETAIL: "/encounters/:id",
  LAB_ORDERS: "/lab-orders",
  SETTINGS: "/settings",
  FINANCIAL_MANAGEMENT: "/settings/financial-management",
  TEAM: "/team",
  ORDER_EDIT: "/edit-order/:id",
  ORDER_DETAILS: "/order/:id",
  NOT_FOUND: "*",
  // Child paths (relative to parent route)
  LOGIN_PATH: "login",
  FORGOT_PASSWORD_PATH: "forgot-password",
  RESET_PASSWORD_PATH: "password-reset",
  DASHBOARD_PATH: "dashboard",
  ORDERS_PATH: "orders",
  SUBSCRIPTIONS_PATH: "subscriptions",
  CREATE_SUBSCRIPTION: "/subscriptions/create",
  SUBSCRIPTION_DETAILS: "/subscriptions/:id",
  SUBSCRIPTION_EDIT: "/edit-subscription/:id",
  COUPONS_PATH: "/coupons",
  COUPONS_CREATE: "/coupons/create",
  COUPONS_EDIT: "/coupons/:id/edit",
  PRODUCTS_PATH: "/products",
  PRODUCT_VARIATIONS_PATH: "settings/product-list",
  FINANCIAL_MANAGEMENT_PATH: "/settings/financial-management",
  PRODUCTS_CREATE: "/products/create",
  PRODUCTS_CREATE_EDIT: "/products/create/:id",
  PRODUCTS_EDIT: "products/edit",
  JOURNEYS_PATH: "/journeys",
  JOURNEYS_EDIT: "/journeys/:id/edit",
  PATIENTS_PATH: "/patients",
  PATIENTS_CREATE: "/patients/create",
  SETTINGS_PATH: "settings",
  TEAM_PATH: "team",
  ORGANIZATION_IDENTITY_PATH: "settings/organization-identity",
  WORKFLOW_SETTINGS_PATH: "settings/workflow-settings",
  LAB_ORDER_DETAILS: "lab-orders/:id",
  TWO_FA_PATH: "two-factor",
  TWO_FA: "/two-factor",
} as const;
