export const ROUTES = {
  // Root routes
  ROOT: "/",

  // Guest routes
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/password-reset",
  // Authenticated routes
  DASHBOARD: "/dashboard",
  ORDERS: "/orders",
  ORDERS_CREATE: "/orders/create",
  SUBSCRIPTIONS: "/subscriptions",
  COUPONS: "/coupons",
  PRODUCTS: "/products",
  JOURNEYS: "/journeys",
  JOURNEYS_CREATE: "/journeys/create",
  PATIENTS: "/patients",
  PATIENT_DETAIL: "/patients/:id",
  ENCOUNTERS: "/encounters",
  LAB_ORDERS: "/lab-orders",
  SETTINGS: "/settings",
  TEAM: "/team",
  ORDER_EDIT: "/edit-order/:id",
  ORDER_DETAILS: "/order/:id",

  // Child paths (relative to parent route)
  LOGIN_PATH: "login",
  FORGOT_PASSWORD_PATH: "forgot-password",
  RESET_PASSWORD_PATH: "password-reset",
  DASHBOARD_PATH: "dashboard",
  ORDERS_PATH: "orders",
  SUBSCRIPTIONS_PATH: "subscriptions",
  CREATE_SUBSCRIPTION: "/subscriptions/create",
  SUBSCRIPTION_DETAILS: "/subscriptions/:id",
  COUPONS_PATH: "/coupons",
  COUPONS_CREATE: "/coupons/create",
  COUPONS_EDIT: "/coupons/:id/edit",
  PRODUCTS_PATH: "/products",
  PRODUCTS_CREATE: "/products/create",
  PRODUCTS_EDIT: "/products/edit",
  JOURNEYS_PATH: "/journeys",
  JOURNEYS_EDIT: "/journeys/:id/edit",
  PATIENTS_PATH: "/patients",
  PATIENTS_CREATE: "/patients/create",
  ENCOUNTERS_PATH: "encounters",
  LAB_ORDERS_PATH: "lab-orders",
  LAB_ORDER_DETAILS: "lab-orders/:id",
  SETTINGS_PATH: "settings",
  TEAM_PATH: "team",
} as const;
